Output demo.gif

Set Padding 5
Set WindowBar Colorful

Set FontSize 12
Set Width 1200
Set Height 900

Type "apexlogs"
Sleep 500ms
Enter
Sleep 3s

# Choose thrid option
Down@200ms 3
Enter
Sleep 2s

# Scroll down
Ctrl+d
Sleep 500ms
Ctrl+d
Sleep 500ms
Ctrl+d
Sleep 500ms
Sleep 1s

# Filter
Type "/"
Sleep 500ms
Type "ASSIGNMENT"
Sleep 500ms
Enter
Sleep 2s

# Switch focus
Tab
Sleep 500ms

# Show and hide help
Type "?"
Sleep 2s
Type "?"
Sleep 2s
